import { v4 as uuidv4 } from 'uuid';

export const mockJobs = [
    {
      id: uuidv4(),
      title: "Frontend Developer",
      company: "Tech Solutions",
      location: "New York, NY",
      postedTime: "5 mins ago",
      description: "We are looking for a skilled Frontend Developer...",
    },
    {
      id: uuidv4(),
      title: "Backend Developer",
      company: "Innovatech",
      location: "San Francisco, CA",
      postedTime: "10 mins ago",
      description: "Join our team as a Backend Developer...",
    },
    {
      id: uuidv4(),
      title: "Full Stack Developer",
      company: "Web Works",
      location: "Austin, TX",
      postedTime: "15 mins ago",
      description: "Seeking a Full Stack Developer with experience in...",
    },
    {
      id: uuidv4(),
      title: "Data Scientist",
      company: "Data Corp",
      location: "Seattle, WA",
      postedTime: "20 mins ago",
      description: "We are hiring a Data Scientist to help analyze...",
    },
    {
      id: uuidv4(),
      title: "Product Manager",
      company: "Product Hub",
      location: "Boston, MA",
      postedTime: "25 mins ago",
      description: "Looking for an experienced Product Manager...",
    },
    {
      id: uuidv4(),
      title: "UX/UI Designer",
      company: "Design Studio",
      location: "Denver, CO",
      postedTime: "30 mins ago",
      description: "Join our team as a UX/UI Designer...",
    },
    {
      id: uuidv4(),
      title: "DevOps Engineer",
      company: "Cloud Services",
      location: "Chicago, IL",
      postedTime: "35 mins ago",
      description: "We need a DevOps Engineer to manage our cloud...",
    },
    {
      id: uuidv4(),
      title: "Mobile Developer",
      company: "App Creators",
      location: "Los Angeles, CA",
      postedTime: "40 mins ago",
      description: "Hiring a Mobile Developer to build and maintain...",
    },
    {
      id: uuidv4(),
      title: "System Administrator",
      company: "IT Solutions",
      location: "Miami, FL",
      postedTime: "45 mins ago",
      description: "Seeking a System Administrator to oversee our IT...",
    },
    {
      id: uuidv4(),
      title: "Network Engineer",
      company: "Net Tech",
      location: "Houston, TX",
      postedTime: "50 mins ago",
      description: "We are hiring a Network Engineer to manage our...",
    },
    {
      id: uuidv4(),
      title: "Business Analyst",
      company: "Biz Analytics",
      location: "San Diego, CA",
      postedTime: "55 mins ago",
      description: "Looking for a Business Analyst to help us improve...",
    },
    {
      id: uuidv4(),
      title: "Software Tester",
      company: "Quality Assurance",
      location: "Orlando, FL",
      postedTime: "1 hour ago",
      description: "We are seeking a Software Tester to ensure our...",
    },
    {
      id: uuidv4(),
      title: "Marketing Manager",
      company: "Market Masters",
      location: "New York, NY",
      postedTime: "1 hour ago",
      description: "Join our team as a Marketing Manager to lead our...",
    },
    {
      id: uuidv4(),
      title: "HR Specialist",
      company: "HR Hub",
      location: "San Francisco, CA",
      postedTime: "1 hour ago",
      description: "We are looking for an HR Specialist to manage our...",
    },
    {
      id: uuidv4(),
      title: "Content Writer",
      company: "Write It",
      location: "Austin, TX",
      postedTime: "1 hour ago",
      description: "Hiring a Content Writer to create compelling content...",
    },
    {
      id: uuidv4(),
      title: "SEO Specialist",
      company: "SEO Experts",
      location: "Seattle, WA",
      postedTime: "1 hour ago",
      description: "We need an SEO Specialist to improve our online...",
    },
    {
      id: uuidv4(),
      title: "Graphic Designer",
      company: "Creative Designs",
      location: "Boston, MA",
      postedTime: "1 hour ago",
      description: "Join our team as a Graphic Designer to create visual...",
    },
    {
      id: uuidv4(),
      title: "Sales Manager",
      company: "Sales Force",
      location: "Denver, CO",
      postedTime: "1 hour ago",
      description: "Looking for a Sales Manager to lead our sales team...",
    },
    {
      id: uuidv4(),
      title: "Customer Support",
      company: "Support Services",
      location: "Chicago, IL",
      postedTime: "1 hour ago",
      description: "We are hiring a Customer Support representative to...",
    },
    {
      id: uuidv4(),
      title: "Financial Analyst",
      company: "Finance Hub",
      location: "Los Angeles, CA",
      postedTime: "1 hour ago",
      description: "Seeking a Financial Analyst to help us with financial...",
    },
    {
      id: uuidv4(),
      title: "Operations Manager",
      company: "Operations Inc.",
      location: "Miami, FL",
      postedTime: "1 hour ago",
      description: "We need an Operations Manager to oversee our...",
    },
    {
      id: uuidv4(),
      title: "Project Manager",
      company: "Projects R Us",
      location: "Houston, TX",
      postedTime: "1 hour ago",
      description: "Join our team as a Project Manager to manage and...",
    },
    {
      id: uuidv4(),
      title: "Social Media Manager",
      company: "Social Sphere",
      location: "San Diego, CA",
      postedTime: "1 hour ago",
      description: "We are looking for a Social Media Manager to handle...",
    },
    {
      id: uuidv4(),
      title: "IT Support",
      company: "Tech Help",
      location: "Orlando, FL",
      postedTime: "1 hour ago",
      description: "Hiring IT Support to assist with technical issues...",
    },
    {
      id: uuidv4(),
      title: "Web Developer",
      company: "Web Wizards",
      location: "New York, NY",
      postedTime: "1 hour ago",
      description: "We need a Web Developer to build and maintain our...",
    },
    {
      id: uuidv4(),
      title: "Data Analyst",
      company: "Data Insights",
      location: "San Francisco, CA",
      postedTime: "1 hour ago",
      description: "Seeking a Data Analyst to help us with data...",
    },
    {
      id: uuidv4(),
      title: "Machine Learning Engineer",
      company: "AI Innovations",
      location: "Austin, TX",
      postedTime: "1 hour ago",
      description: "Join our team as a Machine Learning Engineer to...",
    },
    {
      id: uuidv4(),
      title: "Cybersecurity Specialist",
      company: "SecureTech",
      location: "Seattle, WA",
      postedTime: "1 hour ago",
      description: "We are hiring a Cybersecurity Specialist to protect...",
    },
    {
      id: uuidv4(),
      title: "Recruiter",
      company: "Talent Finders",
      location: "Boston, MA",
      postedTime: "1 hour ago",
      description: "Looking for a Recruiter to help us find top talent...",
    },
    {
      id: uuidv4(),
      title: "Technical Writer",
      company: "Docs Inc.",
      location: "Denver, CO",
      postedTime: "1 hour ago",
      description: "We need a Technical Writer to create documentation...",
    },
  ];
  