export const ROUTES = {
    LANDINGPAGE: "/",
    TALENT_GALLERY: "/talents",
    VIDEO_DETAILS: "/video/:id",
    JOB_BOARD: "/job-board",
    CART: "/cart",
    JOB_DETAIL: "/job-board/:id",
    EMPLOYER: "/employer",
    EMPLOYER_DASHBOARD: "dashboard",
    EMPLOYER_PROFILE: "profile/:id",
    EMPLOYER_ADVERTISEMENT: "advertisement",
    EMPLOYER_ADVERTISEMENT_MANAGE: "advertisement/manage/:id",
    EMPLOYER_VIDEO_MANAGEMENT: "video-management",
    EMPLOYER_GUIDELINE: "video-guideline",
    ADMIN: "/admin",
    ADMIN_DASHBOARD: "dashboard",
    ADMIN_USER_MANAGEMENT: "user-management",
    ADMIN_CONTENT_MANAGEMENT: "content-management",
    ADMIN_ADVERTISEMENT_MANAGEMENT: "advertisement-management",
    ADMIN_ORDER_MANAGEMENT: "order-management",
    ADMIN_ORDER_MANAGEMENT_BY_ID: "order-management/:id",
    ADMIN_GUIDELINE: "video-guideline",
    CANDIDATE: "/candidate",
    CANDIDATE_DASHBOARD: "dashboard",
    CANDIDATE_VIDEO_MANAGEMENT: "video-management",
    CANDIDATE_VIDEO_DETAIL: "video-management/:id",
    CANDIDATE_VACANCIES: "vacancies",
    CANDIDATE_PROFILE: "profile/:id",
    CANDIDATE_FAQ: "faq",
    CANDIDATE_PAYMENT: "payment",
    CANDIDATE_VIDEO_GUIDELINE: "video-guideline",
    RESET_PASSWORD: "/reset-password",
    HOME: "/Home",
    AUTH: "/auth/",
    LOGIN: "login",
    NOT_FOUND: "/Home",
  };
  